version: "2"

services:
  backend:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./backend:/code
      - ./database_data:/code/database_data
    ports:
      - "5000:5000"
    networks:
      - main
  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.cfg:/etc/nginx/nginx.conf:ro
    networks:
      - main
    depends_on:
      - frontend
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/app/'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - main
networks:
  main:
    driver: bridge