FROM python:3.8

WORKDIR /code/
ADD . .
RUN pip install pipenv
RUN pipenv install --system
ENV FLASK_APP=app
ENV FLASK_ENV=development
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]